version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build:"
    target-branch: "main"
    reviewers:
      - "leviem1"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps:"
    target-branch: "main"
    reviewers:
      - "leviem1"
